-- DANYEODAM Stage 0 service-access, recovery, event-ingestion, and
-- physical-interest server RPCs.
--
-- Plain invite and recovery codes are generated by the Node.js server and are
-- never accepted by this database surface. These functions accept only
-- lowercase/uppercase hexadecimal SHA-256 digests and store them as 32-byte
-- bytea values.

-- -------------------------------------------------------------------------
-- One-use participant invitations and generic redeem throttling
-- -------------------------------------------------------------------------

create table private.participant_invite_codes (
  id uuid primary key default gen_random_uuid(),
  code_hash bytea not null unique check (octet_length(code_hash) = 32),
  entropy_bits smallint not null default 128 check (entropy_bits = 128),
  issued_by_auth_user_id uuid references auth.users(id) on delete set null,
  note text check (note is null or char_length(note) between 1 and 200),
  issued_at timestamptz not null default now(),
  redeemed_at timestamptz,
  redeemed_by_user_id uuid references public.app_users(id) on delete set null,
  constraint participant_invite_codes_redeem_state check (
    (redeemed_at is null and redeemed_by_user_id is null)
    or (redeemed_at is not null and redeemed_by_user_id is not null)
  ),
  constraint participant_invite_codes_redeemed_after_issue check (
    redeemed_at is null or redeemed_at >= issued_at
  )
);

create index participant_invite_codes_issued_by_idx
  on private.participant_invite_codes(issued_by_auth_user_id)
  where issued_by_auth_user_id is not null;

create index participant_invite_codes_redeemed_by_idx
  on private.participant_invite_codes(redeemed_by_user_id)
  where redeemed_by_user_id is not null;

create table private.participant_redeem_limits (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  window_started_at timestamptz not null default now(),
  failed_attempts smallint not null default 0
    check (failed_attempts between 0 and 5),
  locked_until timestamptz,
  updated_at timestamptz not null default now(),
  constraint participant_redeem_limits_lock_after_window check (
    locked_until is null or locked_until >= window_started_at
  )
);

create trigger participant_redeem_limits_set_updated_at
before update on private.participant_redeem_limits
for each row execute function private.set_updated_at();

alter table private.participant_invite_codes enable row level security;
alter table private.participant_invite_codes force row level security;
alter table private.participant_redeem_limits enable row level security;
alter table private.participant_redeem_limits force row level security;

revoke all on table private.participant_invite_codes
  from public, anon, authenticated, service_role;
revoke all on table private.participant_redeem_limits
  from public, anon, authenticated, service_role;

-- -------------------------------------------------------------------------
-- Recovery-claim serialization for existing protected acquisition writes
-- -------------------------------------------------------------------------

-- This definition intentionally preserves the v0.2.2 acquisition contract.
-- The only authorization change is a fresh auth.users check plus FOR SHARE on
-- the active identity row. claim_recovery_code takes that row FOR UPDATE.
create or replace function api_private.acquire_commit(
  p_auth_user_id uuid,
  p_spot_id uuid,
  p_idempotency_key uuid,
  p_public_gate_open boolean,
  p_expected_spot_updated_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_existing record;
  v_spot record;
  v_card record;
  v_acquisition_id uuid;
  v_sequence bigint;
  v_acquired_at timestamptz := clock_timestamp();
  v_acquired_on_kst date;
  v_implausible boolean;
begin
  if p_auth_user_id is null then
    return jsonb_build_object('status', 'error', 'code', 'UNAUTHORIZED');
  end if;

  select identity_row.user_id
  into v_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null
  for share of identity_row;

  if v_user_id is null then
    return jsonb_build_object('status', 'error', 'code', 'UNAUTHORIZED');
  end if;

  if not coalesce(p_public_gate_open, false)
    and not exists (
      select 1
      from private.participant_access as access_row
      where access_row.user_id = v_user_id
        and access_row.revoked_at is null
        and (
          access_row.expires_at is null
          or access_row.expires_at > clock_timestamp()
        )
    )
  then
    return jsonb_build_object('status', 'error', 'code', 'GATE_CLOSED');
  end if;

  if p_spot_id is null or p_idempotency_key is null then
    return jsonb_build_object('status', 'error', 'code', 'NOT_FOUND');
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'danyeodam:acquire:idempotency:' || v_user_id::text || ':' ||
      p_idempotency_key::text,
      0
    )
  );

  select
    acquisition_row.id,
    acquisition_row.spot_id,
    acquisition_row.acquisition_type
  into v_existing
  from public.acquisitions as acquisition_row
  where acquisition_row.user_id = v_user_id
    and acquisition_row.idempotency_key = p_idempotency_key;

  if found then
    if v_existing.spot_id = p_spot_id
      and v_existing.acquisition_type = 'field'
    then
      return private.acquire_result(v_existing.id, 'replay');
    end if;

    return jsonb_build_object(
      'status', 'error',
      'code', 'IDEMPOTENCY_CONFLICT'
    );
  end if;

  select
    spot_row.id,
    spot_row.status,
    spot_row.latitude,
    spot_row.longitude,
    spot_row.radius_m,
    spot_row.accuracy_threshold_m,
    spot_row.updated_at
  into v_spot
  from public.spots as spot_row
  where spot_row.id = p_spot_id;

  if not found then
    return jsonb_build_object('status', 'error', 'code', 'NOT_FOUND');
  end if;

  if v_spot.status <> 'open' then
    return jsonb_build_object('status', 'error', 'code', 'SPOT_NOT_OPEN');
  end if;

  if p_expected_spot_updated_at is null
    or v_spot.updated_at <> p_expected_spot_updated_at
  then
    return jsonb_build_object(
      'status', 'error',
      'code', 'SPOT_CONFIG_CHANGED'
    );
  end if;

  select
    card_row.id,
    card_row.title_ko,
    card_row.title_en,
    card_row.sketch_path,
    card_row.color_hex
  into v_card
  from public.cards as card_row
  where card_row.spot_id = p_spot_id
    and card_row.kind = 'region'
    and card_row.is_published
    and card_row.sketch_path is not null
  order by card_row.published_at desc, card_row.id
  limit 1;

  if not found then
    return jsonb_build_object('status', 'error', 'code', 'SPOT_NOT_OPEN');
  end if;

  v_acquired_on_kst := (v_acquired_at at time zone 'Asia/Seoul')::date;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'danyeodam:acquire:daily:' || v_user_id::text || ':' ||
      p_spot_id::text || ':' || v_acquired_on_kst::text,
      0
    )
  );

  if exists (
    select 1
    from public.acquisitions as acquisition_row
    where acquisition_row.user_id = v_user_id
      and acquisition_row.spot_id = p_spot_id
      and acquisition_row.acquisition_type = 'field'
      and acquisition_row.acquired_on_kst = v_acquired_on_kst
  ) then
    return jsonb_build_object(
      'status', 'error',
      'code', 'ALREADY_ACQUIRED_TODAY'
    );
  end if;

  v_implausible := private.is_implausible_poi_transition(
    v_user_id,
    p_spot_id,
    v_acquired_at
  );

  begin
    insert into private.card_counters (card_id, last_sequence, updated_at)
    values (v_card.id, 1, v_acquired_at)
    on conflict (card_id) do update
    set last_sequence = private.card_counters.last_sequence + 1,
        updated_at = excluded.updated_at
    returning last_sequence into v_sequence;

    insert into public.acquisitions (
      user_id,
      spot_id,
      card_id,
      acquisition_type,
      verification_result,
      idempotency_key,
      field_sequence,
      implausible_transition,
      acquired_at
    )
    values (
      v_user_id,
      p_spot_id,
      v_card.id,
      'field',
      'passed',
      p_idempotency_key,
      v_sequence,
      v_implausible,
      v_acquired_at
    )
    returning id into v_acquisition_id;

    insert into analytics.events (
      user_id,
      event_name,
      source,
      occurred_at,
      spot_id,
      properties
    )
    values (
      v_user_id,
      'acquire_success',
      'server',
      v_acquired_at,
      p_spot_id,
      jsonb_build_object('spot_id', p_spot_id)
    );
  exception
    when unique_violation then
      select
        acquisition_row.id,
        acquisition_row.spot_id,
        acquisition_row.acquisition_type
      into v_existing
      from public.acquisitions as acquisition_row
      where acquisition_row.user_id = v_user_id
        and acquisition_row.idempotency_key = p_idempotency_key;

      if found then
        if v_existing.spot_id = p_spot_id
          and v_existing.acquisition_type = 'field'
        then
          return private.acquire_result(v_existing.id, 'replay');
        end if;

        return jsonb_build_object(
          'status', 'error',
          'code', 'IDEMPOTENCY_CONFLICT'
        );
      end if;

      if exists (
        select 1
        from public.acquisitions as acquisition_row
        where acquisition_row.user_id = v_user_id
          and acquisition_row.spot_id = p_spot_id
          and acquisition_row.acquisition_type = 'field'
          and acquisition_row.acquired_on_kst = v_acquired_on_kst
      ) then
        return jsonb_build_object(
          'status', 'error',
          'code', 'ALREADY_ACQUIRED_TODAY'
        );
      end if;

      raise;
  end;

  return private.acquire_result(v_acquisition_id, 'created');
end;
$$;

create or replace function api_private.record_acquire_failure(
  p_auth_user_id uuid,
  p_spot_id uuid,
  p_code text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_spot_id uuid;
begin
  if p_code is null or p_code not in (
    'OUT_OF_RANGE',
    'LOW_ACCURACY',
    'ALREADY_ACQUIRED_TODAY',
    'SPOT_NOT_OPEN',
    'GATE_CLOSED'
  ) then
    raise exception 'unsupported acquire failure code'
      using errcode = '22023';
  end if;

  select identity_row.user_id
  into v_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null
  for share of identity_row;

  if v_user_id is null then
    return false;
  end if;

  select spot_row.id
  into v_spot_id
  from public.spots as spot_row
  where spot_row.id = p_spot_id;

  insert into analytics.events (
    user_id,
    event_name,
    source,
    occurred_at,
    spot_id,
    properties
  )
  values (
    v_user_id,
    'acquire_fail',
    'server',
    clock_timestamp(),
    v_spot_id,
    jsonb_build_object('code', p_code)
  );

  return true;
end;
$$;

-- -------------------------------------------------------------------------
-- Participant invitation administration and redemption
-- -------------------------------------------------------------------------

create or replace function api_private.issue_participant_invites(
  p_auth_user_id uuid,
  p_code_hash_hexes text[],
  p_note text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
  v_user_id uuid;
begin
  if p_auth_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  -- Every protected write locks the active binding in SHARE mode. Recovery
  -- claim takes the same row FOR UPDATE, so either this write commits first or
  -- it observes the revoked binding and returns unauthorized.
  select identity_row.user_id
  into v_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null
  for share of identity_row;

  if v_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  -- Authorization is based only on the fresh server-controlled table. User
  -- metadata and JWT claims are deliberately ignored.
  if not exists (
    select 1
    from private.admin_members as admin_row
    where admin_row.auth_user_id = p_auth_user_id
      and admin_row.revoked_at is null
  ) then
    return jsonb_build_object('status', 'forbidden');
  end if;

  v_count := cardinality(p_code_hash_hexes);
  if v_count is null
    or v_count < 1
    or v_count > 20
    or p_note is not null
       and (char_length(btrim(p_note)) < 1 or char_length(p_note) > 200)
    or exists (
      select 1
      from unnest(p_code_hash_hexes) as supplied_hash(code_hash_hex)
      where supplied_hash.code_hash_hex is null
        or supplied_hash.code_hash_hex !~ '^[0-9A-Fa-f]{64}$'
    )
    or (
      select count(*)
      from unnest(p_code_hash_hexes) as supplied_hash(code_hash_hex)
    ) <> (
      select count(distinct lower(supplied_hash.code_hash_hex))
      from unnest(p_code_hash_hexes) as supplied_hash(code_hash_hex)
    )
  then
    raise exception 'invalid participant invitation issue request'
      using errcode = '22023';
  end if;

  insert into private.participant_invite_codes (
    code_hash,
    issued_by_auth_user_id,
    note
  )
  select
    decode(lower(supplied_hash.code_hash_hex), 'hex'),
    p_auth_user_id,
    p_note
  from unnest(p_code_hash_hexes) as supplied_hash(code_hash_hex);

  return jsonb_build_object('status', 'created', 'count', v_count);
end;
$$;

create or replace function api_private.redeem_participant_invite(
  p_auth_user_id uuid,
  p_code_hash_hex text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_invite_id uuid;
  v_now timestamptz := clock_timestamp();
  v_limit private.participant_redeem_limits%rowtype;
  v_failed_attempts smallint;
  v_locked_until timestamptz;
begin
  if p_auth_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  select identity_row.user_id
  into v_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null
  for share of identity_row;

  if v_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  insert into private.participant_redeem_limits (
    auth_user_id,
    window_started_at,
    failed_attempts,
    locked_until,
    updated_at
  )
  values (p_auth_user_id, v_now, 0, null, v_now)
  on conflict (auth_user_id) do nothing;

  select limit_row.*
  into v_limit
  from private.participant_redeem_limits as limit_row
  where limit_row.auth_user_id = p_auth_user_id
  for update;

  if v_limit.locked_until is not null and v_limit.locked_until > v_now then
    return jsonb_build_object(
      'status', 'rate_limited',
      'locked_minutes', greatest(
        1,
        ceil(extract(epoch from (v_limit.locked_until - v_now)) / 60)::integer
      )
    );
  end if;

  if v_limit.window_started_at <= v_now - interval '15 minutes' then
    update private.participant_redeem_limits
    set window_started_at = v_now,
        failed_attempts = 0,
        locked_until = null,
        updated_at = v_now
    where auth_user_id = p_auth_user_id;

    v_limit.window_started_at := v_now;
    v_limit.failed_attempts := 0;
    v_limit.locked_until := null;
  end if;

  if p_code_hash_hex is not null
    and p_code_hash_hex ~ '^[0-9A-Fa-f]{64}$'
  then
    select invite_row.id
    into v_invite_id
    from private.participant_invite_codes as invite_row
    where invite_row.code_hash = decode(lower(p_code_hash_hex), 'hex')
      and invite_row.redeemed_at is null
    for update;
  end if;

  if v_invite_id is not null then
    insert into private.participant_access (
      user_id,
      access_kind,
      granted_at,
      granted_by_auth_user_id,
      expires_at,
      revoked_at
    )
    values (
      v_user_id,
      'internal_tester',
      v_now,
      null,
      null,
      null
    )
    on conflict (user_id) do update
    set access_kind = 'internal_tester',
        granted_at = excluded.granted_at,
        granted_by_auth_user_id = null,
        expires_at = null,
        revoked_at = null;

    update private.participant_invite_codes
    set redeemed_at = v_now,
        redeemed_by_user_id = v_user_id
    where id = v_invite_id
      and redeemed_at is null;

    delete from private.participant_redeem_limits
    where auth_user_id = p_auth_user_id;

    return jsonb_build_object('status', 'redeemed');
  end if;

  v_failed_attempts := least(5, v_limit.failed_attempts + 1);
  if v_failed_attempts >= 5 then
    v_locked_until := v_now + interval '15 minutes';
  else
    v_locked_until := null;
  end if;

  update private.participant_redeem_limits
  set failed_attempts = v_failed_attempts,
      locked_until = v_locked_until,
      updated_at = v_now
  where auth_user_id = p_auth_user_id;

  if v_locked_until is not null then
    return jsonb_build_object(
      'status', 'rate_limited',
      'locked_minutes', 15
    );
  end if;

  return jsonb_build_object('status', 'not_found');
end;
$$;

-- -------------------------------------------------------------------------
-- Recovery issue and claim
-- -------------------------------------------------------------------------

create or replace function api_private.issue_recovery_code(
  p_auth_user_id uuid,
  p_code_hash_hex text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_rechecked_user_id uuid;
  v_now timestamptz := clock_timestamp();
begin
  if p_auth_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  select identity_row.user_id
  into v_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null;

  if v_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  -- issue and claim use the same per-target lock before touching either the
  -- target identity or its code rows. This removes the former
  -- identity->code / code->identity deadlock cycle.
  perform pg_advisory_xact_lock(
    hashtextextended('danyeodam:recovery:target:' || v_user_id::text, 0)
  );

  select identity_row.user_id
  into v_rechecked_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.user_id = v_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null
  for share of identity_row;

  if v_rechecked_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  if not exists (
    select 1
    from public.acquisitions as acquisition_row
    where acquisition_row.user_id = v_user_id
  ) then
    return jsonb_build_object('status', 'no_acquisition');
  end if;

  if p_code_hash_hex is null
    or p_code_hash_hex !~ '^[0-9A-Fa-f]{64}$'
  then
    raise exception 'invalid recovery code digest'
      using errcode = '22023';
  end if;

  update private.recovery_codes
  set revoked_at = v_now
  where user_id = v_user_id
    and revoked_at is null
    and claimed_at is null;

  insert into private.recovery_codes (
    user_id,
    code_hash,
    issued_at
  )
  values (
    v_user_id,
    decode(lower(p_code_hash_hex), 'hex'),
    v_now
  );

  return jsonb_build_object('status', 'issued');
end;
$$;

create or replace function api_private.claim_recovery_code(
  p_auth_user_id uuid,
  p_code_hash_hex text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_user_id uuid;
  v_target_user_id uuid;
  v_expected_target_user_id uuid;
  v_recovery_code_id uuid;
  v_is_anonymous boolean;
  v_now timestamptz := clock_timestamp();
  v_limit private.recovery_claim_limits%rowtype;
  v_failed_attempts smallint;
  v_locked_until timestamptz;
begin
  if p_auth_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  select identity_row.user_id, coalesce(auth_user.is_anonymous, false)
  into v_current_user_id, v_is_anonymous
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null;

  if v_current_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  if not v_is_anonymous then
    return jsonb_build_object('status', 'not_anonymous');
  end if;

  -- API-CONTRACT section 6 defines "empty" as zero acquisitions. Other
  -- pre-claim state is merged below where meaningful; data that cannot be
  -- safely moved (for example a still-pending temp upload path) keeps the old
  -- app_user row alive for later cleanup rather than broadening not_empty.
  if exists (
      select 1 from public.acquisitions as row_data
      where row_data.user_id = v_current_user_id
    )
  then
    return jsonb_build_object('status', 'not_empty');
  end if;

  insert into private.recovery_claim_limits (
    auth_user_id,
    window_started_at,
    failed_attempts,
    locked_until,
    updated_at
  )
  values (p_auth_user_id, v_now, 0, null, v_now)
  on conflict (auth_user_id) do nothing;

  select limit_row.*
  into v_limit
  from private.recovery_claim_limits as limit_row
  where limit_row.auth_user_id = p_auth_user_id
  for update;

  if v_limit.locked_until is not null and v_limit.locked_until > v_now then
    return jsonb_build_object(
      'status', 'rate_limited',
      'locked_minutes', greatest(
        1,
        ceil(extract(epoch from (v_limit.locked_until - v_now)) / 60)::integer
      )
    );
  end if;

  if v_limit.window_started_at <= v_now - interval '15 minutes' then
    update private.recovery_claim_limits
    set window_started_at = v_now,
        failed_attempts = 0,
        locked_until = null,
        updated_at = v_now
    where auth_user_id = p_auth_user_id;

    v_limit.window_started_at := v_now;
    v_limit.failed_attempts := 0;
    v_limit.locked_until := null;
  end if;

  if p_code_hash_hex is not null
    and p_code_hash_hex ~ '^[0-9A-Fa-f]{64}$'
  then
    select code_row.id, code_row.user_id
    into v_recovery_code_id, v_target_user_id
    from private.recovery_codes as code_row
    where code_row.code_hash = decode(lower(p_code_hash_hex), 'hex')
      and code_row.revoked_at is null
      and code_row.claimed_at is null
      and (code_row.expires_at is null or code_row.expires_at > v_now);
  end if;

  if v_recovery_code_id is not null then
    v_expected_target_user_id := v_target_user_id;

    -- Recovery issue and claim take this same exclusive per-target lock
    -- before identity/code row locks. The target was discovered without a row
    -- lock and is revalidated below after serialization.
    perform pg_advisory_xact_lock(
      hashtextextended(
        'danyeodam:recovery:target:' || v_expected_target_user_id::text,
        0
      )
    );

    -- Claim is the only operation taking identity rows FOR UPDATE. Every
    -- protected write takes its active identity FOR SHARE, so writes either
    -- finish before this point or re-evaluate the revoked row afterward.
    perform identity_row.id
    from private.user_identities as identity_row
    where identity_row.revoked_at is null
      and (
        identity_row.user_id in (
          v_current_user_id,
          v_expected_target_user_id
        )
        or identity_row.auth_user_id = p_auth_user_id
      )
    order by identity_row.user_id::text, identity_row.auth_user_id::text
    for update;

    select identity_row.user_id, coalesce(auth_user.is_anonymous, false)
    into v_current_user_id, v_is_anonymous
    from private.user_identities as identity_row
    join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
    where identity_row.auth_user_id = p_auth_user_id
      and identity_row.user_id = v_current_user_id
      and identity_row.revoked_at is null
      and auth_user.deleted_at is null;

    if v_current_user_id is null then
      return jsonb_build_object('status', 'unauthorized');
    end if;

    if not v_is_anonymous then
      return jsonb_build_object('status', 'not_anonymous');
    end if;

    if exists (
      select 1
      from public.acquisitions as acquisition_row
      where acquisition_row.user_id = v_current_user_id
    ) then
      return jsonb_build_object('status', 'not_empty');
    end if;

    v_recovery_code_id := null;
    v_target_user_id := null;

    select code_row.id, code_row.user_id
    into v_recovery_code_id, v_target_user_id
    from private.recovery_codes as code_row
    where code_row.code_hash = decode(lower(p_code_hash_hex), 'hex')
      and code_row.user_id = v_expected_target_user_id
      and code_row.revoked_at is null
      and code_row.claimed_at is null
      and (code_row.expires_at is null or code_row.expires_at > v_now)
    for update;
  end if;

  if v_recovery_code_id is null then
    v_failed_attempts := least(5, v_limit.failed_attempts + 1);
    if v_failed_attempts >= 5 then
      v_locked_until := v_now + interval '15 minutes';
    else
      v_locked_until := null;
    end if;

    update private.recovery_claim_limits
    set failed_attempts = v_failed_attempts,
        locked_until = v_locked_until,
        updated_at = v_now
    where auth_user_id = p_auth_user_id;

    if v_locked_until is not null then
      return jsonb_build_object(
        'status', 'rate_limited',
        'locked_minutes', 15
      );
    end if;

    return jsonb_build_object('status', 'not_found');
  end if;

  if not exists (
    select 1
    from private.user_identities as identity_row
    where identity_row.auth_user_id = p_auth_user_id
      and identity_row.user_id = v_current_user_id
      and identity_row.revoked_at is null
  ) then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  update private.user_identities
  set revoked_at = v_now
  where revoked_at is null
    and (
      user_id = v_target_user_id
      or auth_user_id = p_auth_user_id
    );

  insert into private.user_identities (
    auth_user_id,
    user_id,
    bound_at
  )
  values (p_auth_user_id, v_target_user_id, v_now);

  update private.recovery_codes
  set claimed_at = v_now,
      claimed_by_auth_user_id = p_auth_user_id
  where id = v_recovery_code_id
    and revoked_at is null
    and claimed_at is null;

  if not found then
    raise exception 'recovery code was consumed concurrently'
      using errcode = '40001';
  end if;

  -- A tester who redeems an invite before recovering still has to retain
  -- access while PUBLIC_RECRUIT_GATE is closed. Merge the active entitlement
  -- into the recovered logical user before the disposable user is removed.
  insert into private.participant_access (
    user_id,
    access_kind,
    granted_at,
    granted_by_auth_user_id,
    expires_at,
    revoked_at
  )
  select
    v_target_user_id,
    access_row.access_kind,
    least(access_row.granted_at, v_now),
    access_row.granted_by_auth_user_id,
    access_row.expires_at,
    null
  from private.participant_access as access_row
  where access_row.user_id = v_current_user_id
    and access_row.revoked_at is null
    and (access_row.expires_at is null or access_row.expires_at > v_now)
  on conflict (user_id) do update
  set access_kind = case
        when private.participant_access.access_kind = 'public_beta'
          or excluded.access_kind = 'public_beta'
          then 'public_beta'
        else 'internal_tester'
      end,
      granted_at = least(
        private.participant_access.granted_at,
        excluded.granted_at
      ),
      expires_at = case
        when private.participant_access.expires_at is null
          or excluded.expires_at is null
          then null
        else greatest(
          private.participant_access.expires_at,
          excluded.expires_at
        )
      end,
      revoked_at = null;

  -- Preserve non-acquisition demand and telemetry already attached to the
  -- disposable logical user. Client-event conflicts are deduplicated by the
  -- existing (user_id, client_event_id) partial unique index.
  insert into public.physical_requests (user_id, kind, created_at)
  select v_target_user_id, request_row.kind, request_row.created_at
  from public.physical_requests as request_row
  where request_row.user_id = v_current_user_id
  on conflict (user_id, kind) do nothing;

  insert into analytics.events (
    client_event_id,
    user_id,
    event_name,
    source,
    occurred_at,
    received_at,
    spot_id,
    properties
  )
  select
    event_row.client_event_id,
    v_target_user_id,
    event_row.event_name,
    event_row.source,
    event_row.occurred_at,
    event_row.received_at,
    event_row.spot_id,
    event_row.properties
  from analytics.events as event_row
  where event_row.user_id = v_current_user_id
  on conflict do nothing;

  delete from analytics.events
  where user_id = v_current_user_id;

  delete from public.physical_requests
  where user_id = v_current_user_id;

  delete from private.participant_access
  where user_id = v_current_user_id;

  delete from private.recovery_claim_limits
  where auth_user_id = p_auth_user_id;

  delete from public.app_users as app_user
  where app_user.id = v_current_user_id
    and not exists (
      select 1
      from private.user_identities as identity_row
      where identity_row.user_id = app_user.id
        and identity_row.revoked_at is null
    )
    and not exists (
      select 1 from public.acquisitions as row_data
      where row_data.user_id = app_user.id
    )
    and not exists (
      select 1 from public.personal_cards as row_data
      where row_data.user_id = app_user.id
    )
    and not exists (
      select 1 from public.physical_requests as row_data
      where row_data.user_id = app_user.id
    )
    and not exists (
      select 1 from private.participant_access as row_data
      where row_data.user_id = app_user.id
    )
    and not exists (
      select 1 from private.recovery_codes as row_data
      where row_data.user_id = app_user.id
    )
    and not exists (
      select 1 from private.personal_card_temp_uploads as row_data
      where row_data.user_id = app_user.id
    )
    and not exists (
      select 1 from analytics.events as row_data
      where row_data.user_id = app_user.id
    );

  return jsonb_build_object('status', 'restored');
end;
$$;

-- A small server-only check for protected operations that do not otherwise
-- enter a product RPC (for example /api/auth/link-email). It deliberately
-- returns no logical user identifier.
create or replace function api_private.has_active_identity(
  p_auth_user_id uuid
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'status',
    case
      when p_auth_user_id is not null
        and exists (
          select 1
          from auth.users as auth_user
          join private.user_identities as identity_row
            on identity_row.auth_user_id = auth_user.id
           and identity_row.revoked_at is null
          where auth_user.id = p_auth_user_id
            and auth_user.deleted_at is null
        )
        then 'active'
      else 'inactive'
    end
  )
$$;

-- -------------------------------------------------------------------------
-- Strict client analytics ingestion
-- -------------------------------------------------------------------------

create or replace function api_private.ingest_client_events(
  p_auth_user_id uuid,
  p_public_gate_open boolean,
  p_events jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_event jsonb;
  v_event_name text;
  v_spot_id_text text;
  v_count integer;
  v_accepted integer;
  v_now timestamptz := clock_timestamp();
begin
  if p_auth_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  select identity_row.user_id
  into v_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null
  for share of identity_row;

  if v_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  if not coalesce(p_public_gate_open, false)
    and not exists (
      select 1
      from private.participant_access as access_row
      where access_row.user_id = v_user_id
        and access_row.revoked_at is null
        and (
          access_row.expires_at is null
          or access_row.expires_at > v_now
        )
    )
  then
    return jsonb_build_object('status', 'gate_closed');
  end if;

  if p_events is null or jsonb_typeof(p_events) <> 'array' then
    return jsonb_build_object('status', 'invalid');
  end if;

  v_count := jsonb_array_length(p_events);
  if v_count < 1 or v_count > 20 then
    return jsonb_build_object('status', 'invalid');
  end if;

  for v_event in
    select input_row.value
    from jsonb_array_elements(p_events) as input_row(value)
  loop
    if jsonb_typeof(v_event) <> 'object'
      or (v_event - array[
        'client_event_id',
        'event_name',
        'occurred_at',
        'spot_id',
        'properties'
      ]::text[]) <> '{}'::jsonb
      or not (
        v_event ?& array[
          'client_event_id',
          'event_name',
          'occurred_at',
          'spot_id',
          'properties'
        ]::text[]
      )
      or jsonb_typeof(v_event -> 'client_event_id') <> 'string'
      or not pg_input_is_valid(v_event ->> 'client_event_id', 'uuid')
      or jsonb_typeof(v_event -> 'event_name') <> 'string'
      or jsonb_typeof(v_event -> 'occurred_at') <> 'string'
      or not pg_input_is_valid(
        v_event ->> 'occurred_at',
        'timestamp with time zone'
      )
      or jsonb_typeof(v_event -> 'properties') <> 'object'
    then
      return jsonb_build_object('status', 'invalid');
    end if;

    v_event_name := v_event ->> 'event_name';
    if v_event_name not in (
      'spot_view',
      'acquire_attempt',
      'personal_card_started',
      'physical_interest_view'
    ) then
      return jsonb_build_object('status', 'invalid');
    end if;

    if (v_event ->> 'occurred_at')::timestamptz < v_now - interval '24 hours'
      or (v_event ->> 'occurred_at')::timestamptz > v_now + interval '5 minutes'
    then
      return jsonb_build_object('status', 'invalid');
    end if;

    if v_event_name = 'physical_interest_view' then
      if jsonb_typeof(v_event -> 'spot_id') <> 'null'
        or v_event -> 'properties' <> '{}'::jsonb
      then
        return jsonb_build_object('status', 'invalid');
      end if;
    else
      if jsonb_typeof(v_event -> 'spot_id') <> 'string'
        or not pg_input_is_valid(v_event ->> 'spot_id', 'uuid')
      then
        return jsonb_build_object('status', 'invalid');
      end if;

      v_spot_id_text := ((v_event ->> 'spot_id')::uuid)::text;
      if v_event -> 'properties'
          <> jsonb_build_object('spot_id', v_spot_id_text)
        or not exists (
          select 1
          from public.spots as spot_row
          where spot_row.id = v_spot_id_text::uuid
        )
      then
        return jsonb_build_object('status', 'invalid');
      end if;
    end if;
  end loop;

  with inserted_events as (
    insert into analytics.events (
      client_event_id,
      user_id,
      event_name,
      source,
      occurred_at,
      spot_id,
      properties
    )
    select
      (input_row.value ->> 'client_event_id')::uuid,
      v_user_id,
      (input_row.value ->> 'event_name')::analytics.event_name,
      'client'::analytics.event_source,
      (input_row.value ->> 'occurred_at')::timestamptz,
      case
        when jsonb_typeof(input_row.value -> 'spot_id') = 'string'
          then (input_row.value ->> 'spot_id')::uuid
        else null
      end,
      input_row.value -> 'properties'
    from jsonb_array_elements(p_events) as input_row(value)
    on conflict do nothing
    returning 1
  )
  select count(*)::integer
  into v_accepted
  from inserted_events;

  return jsonb_build_object(
    'status', 'accepted',
    'accepted', v_accepted,
    'duplicates', v_count - v_accepted
  );
end;
$$;

-- -------------------------------------------------------------------------
-- Physical-production demand signal
-- -------------------------------------------------------------------------

create or replace function api_private.create_physical_request(
  p_auth_user_id uuid,
  p_public_gate_open boolean,
  p_kind text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_request_id uuid;
  v_now timestamptz := clock_timestamp();
begin
  if p_auth_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  select identity_row.user_id
  into v_user_id
  from private.user_identities as identity_row
  join auth.users as auth_user on auth_user.id = identity_row.auth_user_id
  where identity_row.auth_user_id = p_auth_user_id
    and identity_row.revoked_at is null
    and auth_user.deleted_at is null
  for share of identity_row;

  if v_user_id is null then
    return jsonb_build_object('status', 'unauthorized');
  end if;

  if not coalesce(p_public_gate_open, false)
    and not exists (
      select 1
      from private.participant_access as access_row
      where access_row.user_id = v_user_id
        and access_row.revoked_at is null
        and (
          access_row.expires_at is null
          or access_row.expires_at > v_now
        )
    )
  then
    return jsonb_build_object('status', 'gate_closed');
  end if;

  if p_kind is null or p_kind not in ('request', 'notify') then
    raise exception 'invalid physical request kind'
      using errcode = '22023';
  end if;

  insert into public.physical_requests (
    user_id,
    kind,
    created_at
  )
  values (
    v_user_id,
    p_kind::public.physical_request_kind,
    v_now
  )
  on conflict (user_id, kind) do nothing
  returning id into v_request_id;

  if v_request_id is null then
    return jsonb_build_object('status', 'duplicate');
  end if;

  insert into analytics.events (
    user_id,
    event_name,
    source,
    occurred_at,
    properties
  )
  values (
    v_user_id,
    'physical_interest',
    'server',
    v_now,
    '{}'::jsonb
  );

  return jsonb_build_object('status', 'created');
end;
$$;

-- -------------------------------------------------------------------------
-- Function ACLs
-- -------------------------------------------------------------------------

revoke all on function api_private.issue_participant_invites(uuid, text[], text)
  from public, anon, authenticated, service_role;
revoke all on function api_private.redeem_participant_invite(uuid, text)
  from public, anon, authenticated, service_role;
revoke all on function api_private.issue_recovery_code(uuid, text)
  from public, anon, authenticated, service_role;
revoke all on function api_private.claim_recovery_code(uuid, text)
  from public, anon, authenticated, service_role;
revoke all on function api_private.ingest_client_events(uuid, boolean, jsonb)
  from public, anon, authenticated, service_role;
revoke all on function api_private.create_physical_request(uuid, boolean, text)
  from public, anon, authenticated, service_role;
revoke all on function api_private.has_active_identity(uuid)
  from public, anon, authenticated, service_role;

grant execute on function api_private.issue_participant_invites(uuid, text[], text)
  to service_role;
grant execute on function api_private.redeem_participant_invite(uuid, text)
  to service_role;
grant execute on function api_private.issue_recovery_code(uuid, text)
  to service_role;
grant execute on function api_private.claim_recovery_code(uuid, text)
  to service_role;
grant execute on function api_private.ingest_client_events(uuid, boolean, jsonb)
  to service_role;
grant execute on function api_private.create_physical_request(uuid, boolean, text)
  to service_role;
grant execute on function api_private.has_active_identity(uuid)
  to service_role;
